### ISSUE TITLE
Add 1password backend

### ISSUE THREAD

**Issue by frankscholten** [ContainerSolutions/externalsecret-operator#11]
- [x] Create a stub backend and unit test
- [x] Stub backend should return static JSON response from 1password
- [x] Add `op` invocation
- [x] Add `op` to Dockerfile
- [x] Deploy and test operator
- [x] Create scripts for creating, sourcing and deleting kubernetes secrets for the 1password account
- [x] Add deployment with secrets
- [x] Parse secrets from environment to sign in to 1password
- [x] Implement `SignIn` for `OnePasswordCliClient`

**Comment by riccardomc** [comment]
Do you think we could introduce `gosec` in a separate PR, @frankscholten?

**Comment by frankscholten** [comment]
@riccardomc Yes, sounds good.
