### ISSUE TITLE
Adding Table of Content to Readme.md 

### ISSUE THREAD

**Issue by ng29** [ContainerSolutions/externalsecret-operator#110]
Hey @riccardomc  / @frankscholten  / @iamcaleberic 

What would you like to be added:

The idea for Adding Table of Content to Readme.md to add additional enhancement and readability to the docs file.

Why is this needed:

TOC is very useful to hop between the docs/info of the readme and avoids useless scrolling.

**Comment by dbirks** [comment]
If you happen to be using VS Code, I've had good success using the extension `Markdown All in One`. 
Link to the docs for it:
https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one#table-of-contents

**Comment by ng29** [comment]
> If you happen to be using VS Code, I've had good success using the extension `Markdown All in One`.
> Link to the docs for it:
> https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one#table-of-contents

I am not much into VS code but yeah, it will be a decent TOC  ready to serve, so can i pick this up?

**Comment by ng29** [comment]
> > If you happen to be using VS Code, I've had good success using the extension `Markdown All in One`.
> > Link to the docs for it:
> > https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one#table-of-contents
> 
> I am not much into VS code but yeah, it will be a decent TOC ready to serve, so can i work on this ?
