### ISSUE TITLE
Builds on branches failing

### ISSUE THREAD

**Issue by knelasevero** [ContainerSolutions/externalsecret-operator#115]
@dbirks Now builds on PRs work, but not on branches :(

I think that we first need to test if the event name is pull_request to be able to only do that name check on pull resquests.

Wanna take care of this one?

**Comment by dbirks** [comment]
Whoops, missed that. Yes I'll give it a shot :+1:

**Comment by dbirks** [comment]
Rats, looks like even without the 2nd if statement being run, it becomes an invalid conditional :confounded: 

```
    if [[  != ContainerSolutions/externalsecret-operator ]]; then
...
line 20: conditional binary operator expected
```

I'll have to think about that...

**Comment by knelasevero** [comment]
:thinking: since it is template substitution I think you can just

```
REPO_FULL_NAME="${{ github.event.pull_request.head.repo.full_name }}"
```

And then it will always be "" even if its empty.

**Comment by dbirks** [comment]
Hey you're right, I tested it out locally and that works :+1: 
One last PR...
