### ISSUE TITLE
Cannot deploy External Secret on AWS

### ISSUE THREAD

**Issue by udemy-darnone1** [ContainerSolutions/externalsecret-operator#125]
**Describe the solution you'd like**
I would like to deploy this to AWS EKS 

**What is the added value?**
I followed the instructions
1.) in config/backend-config/kustomization.yaml commented out backend-config-dummy.yaml
2.) in config/backend-config/kustomization.yaml uncommented backend-config-asm.yaml
3.) Filled in my AWS details
4.) make deploy failed (MacOS X)

**Give us examples of the outcome**
namespace/externalsecret-operator-system created
customresourcedefinition.apiextensions.k8s.io/externalsecrets.secrets.externalsecret-operator.container-solutions.com created
role.rbac.authorization.k8s.io/externalsecret-operator-leader-election-role created
clusterrole.rbac.authorization.k8s.io/externalsecret-operator-manager-role created
clusterrole.rbac.authorization.k8s.io/externalsecret-operator-proxy-role created
clusterrole.rbac.authorization.k8s.io/externalsecret-operator-metrics-reader created
rolebinding.rbac.authorization.k8s.io/externalsecret-operator-leader-election-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/externalsecret-operator-manager-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/externalsecret-operator-proxy-rolebinding created
secret/externalsecret-operator-config created
service/externalsecret-operator-controller-manager-metrics-service created
deployment.apps/externalsecret-operator-controller-manager created
**error: unable to recognize "STDIN": no matches for kind "ExternalSecret" in version "secrets.externalsecret-operator.container-solutions.com/v1alpha1"**

Provide templates if you are proposing changes in the CRD. Provide example workflows or code snippets if they make sense to present.

**Observations (Constraints, Context, etc):**

Give here all extra information that could be interesting. Such as Golang version and Kubernetes version if you are reporting a bug/problem. You can also foresee technical constrains like "this could only be implementing using this specific technology or approach, because of this and that".

Kubectl 1.18.8
AWS EKS 1.17.19
go 1.13.15
Mac OS X 10.14.6

**Comment by knelasevero** [comment]
Hi @udemy-darnone1, thanks for reaching out!

So, before running `make deploy`, you need to run `make install`. `make install` will create the ExternalSecret CRD, and `make deploy` will actually deploy the templates including the template for the ExternalSecret (that needs the CRD to be applied first).

**Comment by udemy-darnone1** [comment]
If that is the case , then your instructions in the README on the main page are missing the make install. Do you need to make  the external secret in config /sample explicitly?  And is this command correct as the secret specifies namespace system:

kubectl get secret externalsecret-operator-externalsecret-sample **-n externalsecret-operator-system** \
  -o jsonpath='{.data.example-externalsecret-key}' | base64 -d
this string is a secret

**Comment by knelasevero** [comment]
Included `make install` in the readme.

We did some big changes recently and we still have to get the docs right for everything. Thanks a lot for pointing things out.

The ExternalSecret that is in the samples template is just an example to see things initially. After having the operator and CRD created on your cluster you can create any ExternalSecret that you desire.

**Comment by knelasevero** [comment]
@udemy-darnone1 hey! Please check the new docs in the repo.

You can deploy with the current image with

IMG=containersol/externalsecret-operator:pr-119 make deploy

Or

IMG=containersol/externalsecret-operator:latest make deploy

Since we are close but not ready yet to make a new release

I will close this issue. Feel free to re open in case of any problems.
