### ISSUE TITLE
1password - Use init and configuration mechanism used by other backends

### ISSUE THREAD

**Issue by riccardomc** [ContainerSolutions/externalsecret-operator#20]
Currently 1password backend uses custom environment variables for its configuration.

After mergin #15, it should use the JSON formatted configuration held in`OPERATOR_CONFIG` environment variable.

**Comment by frankscholten** [comment]
Fixed in https://github.com/ContainerSolutions/externalsecret-operator/commit/4e8cd7af62ed49a7497d1d6fbc22faeb29d5f435
