### ISSUE TITLE
Introduce support for Google Secret Manager

### ISSUE THREAD

**Issue by riccardomc** [ContainerSolutions/externalsecret-operator#3]
Currently [AWS Secrets Manager](https://docs.aws.amazon.com/secretsmanager/latest/userguide/intro.html) is the only supported backend.

[Google Cloud Secret Manager](https://cloud.google.com/solutions/secrets-management/) should also be supported.

**Comment by sethvargo** [comment]
Cloud KMS doesn't actually store secrets. You probably want to integrate with [Google Secret Manager](https://cloud.google.com/secret-manager) instead.
