### ISSUE TITLE
OnePassword - Increase test coverage

### ISSUE THREAD

**Issue by riccardomc** [ContainerSolutions/externalsecret-operator#41]
As per title

**Comment by frankscholten** [comment]
Create a Fake 1Password service that returns realistic API responses when retrieving a secret but is backed by a Go slice and use this to properly test the 1Password backend.

**Comment by frankscholten** [comment]
See https://github.com/ContainerSolutions/externalsecret-operator/tree/refactor/onepassword-cli

**Comment by frankscholten** [comment]
Everything in `onepassword` is tested except a few lines in `op.go` that I can't unit test.
