### ISSUE TITLE
Consider migrating CI from CircleCI to GitHub Actions

### ISSUE THREAD

**Issue by riccardomc** [ContainerSolutions/externalsecret-operator#86]
Currently CI is implemented using CircleCI. It does what it needs to, but GitHub actions would give us a better integration and visibility.

Plus is a good exercise :)

**Comment by Spazzy757** [comment]
I'll take this if you guy don't mind 🤷

**Comment by knelasevero** [comment]
Initial work is done. The Helm and integration test part can come in another issue.
